[supervisord]
nodaemon=true

[program:llama-server]
directory=/app/llama.cpp
command=/app/llama.cpp/build/bin/llama-server --port 8080 --host 0.0.0.0 -m /app/models/tinyllama.gguf -c 2048
autostart=true
autorestart=true

[program:web-server]
directory=/app
command=python3 server.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0